export * as AuthService from './auth.service'
export * as TimetableService from './timetable.service'
export * as TokenService from './token.service'
export * as ResultService from './result.service'
export * as UserService from './user.service'
