# This is a basic workflow to help you get started with Actions

name: AUTO UPDATE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: STOP server and Copy Files
        run: |
          pm2 stop ./ecosystem.config.js
          rm -r /projects/backend/nvestos/src/
          echo "Copying files to Folder"
          cp -r ./* /projects/backend/nvestos/
          echo "NPM run build & Start PM2"
          cd /projects/backend/nvestos/ && npm i && npm run build && pm2 start ./ecosystem.config.js
          echo "Work Done!."